---
name: e2e test with OIDC authentication
on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    uses: Azure/terraform-azurerm-avm-template/.github/workflows/e2e-oidc-template.yml@main
    name: 'Run End to End Tests'
    permissions:
      id-token: write
      contents: read
